#!/bin/bash
set -e

choco install jdk8 -params 'installdir=c:\\jdk' -y
export JAVA_HOME=${JAVA_HOME:-/c/jdk}
export PATH=${JAVA_HOME}/bin:${PATH}

choco install maven -params 'installdir=c:\\mvn' -y
# export PATH=${PATH}:/c/mvn
export PATH=%M2_HOME%\bin:${PATH}

choco install universal-ctags

echo ${PATH}
java -version
mvn -version
