#!/bin/bash
set -e

choco install jdk8 -params 'installdir=c:\\jdk' -y
export JAVA_HOME=${JAVA_HOME:-/c/jdk}
export PATH=${JAVA_HOME}/bin:${PATH}

choco install maven
export MAVEN_HOME=/c/ProgramData/chocolatey/lib/maven
export PATH=${MAVEN_HOME}/bin:${PATH}

choco install universal-ctags

echo ${PATH}
ls ${MAVEN_HOME}

java -version
mvn -version
