#!/bin/bash
set -e

choco install jdk8 -params 'installdir=c:\\jdk' -y
export JAVA_HOME=${JAVA_HOME:-/c/jdk}
export PATH=${JAVA_HOME}/bin:${PATH}

choco install maven
choco install universal-ctags

java -version
mvn -version
